version: '3'
services:
  app-be:
    build: ./backend
    image: 127.0.0.1:5000/antonybudianto/app-be
  app-fe:
    build: ./frontend
    image: 127.0.0.1:5000/antonybudianto/app-fe
    ports:
      - 3000:80
    depends_on:
      - app-be
