apiVersion: v1
kind: Service
metadata:
  name: app-fe
spec:
  selector:
    app: app-fe
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-be
spec:
  selector:
    app: app-be
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-fe
  template:
    metadata:
      labels:
        app: app-fe
    spec:
      containers:
        - name: app-fe
          image: 127.0.0.1:5000/antonybudianto/app-fe
          ports:
            - containerPort: 80
          # https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-be
  template:
    metadata:
      labels:
        app: app-be
    spec:
      containers:
        - name: app-be
          image: 127.0.0.1:5000/antonybudianto/app-be
          ports:
            - containerPort: 5000
